spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:tag-ms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: user
    password: 123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    addresses: amqps://waebvucx:qWtlJy-9NgqOUuVmC8r29m4luRrwkXS_@seal.lmq.cloudamqp.com/waebvucx
    queue:
      tag:
        name: tag-ms.etiqueta.excluida.queue


services:
  word:
    url: https://word-service-aw7r.onrender.com
  tag:
    url: https://tag-ms.onrender.com